volumes:
  platformio_cache:
  esphome_builds:
  esphome_config:

services:
  # 1. Compile the Arduino firmware
  compile-arduino:
    build:
      context: .
      dockerfile: ./.docker/esphome/Dockerfile
    volumes:
      - .:/data
      - platformio_cache:/cache
      - esphome_builds:/builds
      - esphome_config:/data/.docker/esphome/.esphome
    working_dir: /builds
    command: ["compile", "/data/.docker/esphome/test-arduino.yaml"]

  # 2. Compile the ESP-IDF firmware
  compile-espidf:
    build:
      context: .
      dockerfile: ./.docker/esphome/Dockerfile
    volumes:
      - .:/data
      - platformio_cache:/cache
      - esphome_builds:/builds
      - esphome_config:/data/.docker/esphome/.esphome
    working_dir: /builds
    command: ["compile", "/data/.docker/esphome/test-espidf.yaml"]
    depends_on:
      compile-arduino:
        condition: service_completed_successfully
