esphome:
  name: test-mouse-jiggler-espidf
  build_path: /builds/test-mouse-jiggler-espidf

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable BLE
esp32_ble: {}

external_components:
  - source:
      type: local
      path: /data/components

ble_mouse_jiggler:
