esphome:
  name: test-mouse-jiggler-arduino
  build_path: /builds/test-mouse-jiggler-arduino

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable BLE
esp32_ble: {}

external_components:
  - source:
      type: local
      path: /data/components

ble_mouse_jiggler:
