esphome:
  name: test-mouse-jiggler-espidf
  build_path: /builds/test-mouse-jiggler-espidf

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable BLE Server
esp32_ble_server:
  id: ble_server_hub

external_components:
  - source:
      type: local
      path: /data/components

ble_mouse_jiggler:
  ble_server_id: ble_server_hub
