name: ESPHome Component CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create test configuration
        run: |
          echo '
          esp32:
            board: esp32dev

          external_components:
            - source:
                type: local
                path: .

          ble_mouse_jiggler:
            name: "Test Mouse"
          ' > test.yaml
      - name: Build with ESPHome
        uses: esphome/build-action@v2
        with:
          yaml_file: test.yaml
          esphome_version: latest
